set(CMAKE_SYSTEM_NAME $ENV{SYSTEM_NAME})
# message("CMAKE_SYSTEM_NAME:${CMAKE_SYSTEM_NAME}")
set(CMAKE_SYSTEM_PROCESSOR $ENV{SYSTEM_PROCESSOR})
# message("CMAKE_SYSTEM_PROCESSOR:${CMAKE_SYSTEM_PROCESSOR}")

set(CROSS_COMPILE $ENV{CROSS_COMPILE})
# message("CROSS_COMPILE:$ENV{CROSS_COMPILE}")
set(CMAKE_SYSROOT $ENV{SYSROOT})
# message("CMAKE_SYSROOT:$ENV{CMAKE_SYSROOT}")
# set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

set(CMAKE_C_COMPILER $ENV{CC})
# message("CMAKE_C_COMPILER:$ENV{CMAKE_C_COMPILER}")
set(CMAKE_C_FLAGS  $ENV{CFLAGS})
# message("CMAKE_C_FLAGS:$ENV{CMAKE_C_FLAGS}")

set(CMAKE_CXX_COMPILER $ENV{CXX})
# message("CMAKE_CXX_COMPILER:$ENV{CMAKE_CXX_COMPILER}")
set(CMAKE_CXX_FLAGS  $ENV{CXXFLAGS})
# message("CMAKE_CXX_FLAGS:$ENV{CMAKE_CXX_FLAGS}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
# set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)


set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_BUILD_WITH_INSTALL_RPATH on)
list(APPEND CMAKE_MODULE_PATH "$ENV{TOOLCHAIN_DIR}")

